### ISSUE TITLE
Promise is not defined when doing a custom build

### ISSUE THREAD

**Issue by aeakett** [daneden/animate.css#544]
When trying to do a custom build I get the following error when running `gulp`:
```
[10:07:02] 76 animations activated.
[10:07:02] Using gulpfile /asdf/animate.css/gulpfile.js
[10:07:02] Starting 'default'...
[10:07:02] Starting 'createCSS'...
[10:07:02] Finished 'default' after 35 ms

/asdf/animate.css/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:157
        this.processing = new Promise(function (resolve, reject) {
                              ^
ReferenceError: Promise is not defined
    at LazyResult.async (/asdf/animate.css/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/asdf/animate.css/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:79:21)
    at Transform.stream._transform (/asdf/animate.css/node_modules/gulp-postcss/index.js:49:8)
    at Transform._read (_stream_transform.js:179:10)
    at Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:223:10)
    at writeOrBuffer (_stream_writable.js:213:5)
    at Transform.Writable.write (_stream_writable.js:180:11)
    at write (/asdf/animate.css/node_modules/gulp-concat/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/asdf/animate.css/node_modules/gulp-concat/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
```

**Comment by copycut** [comment]
Add that to your task manager file.
```javascript
require('es6-promise').polyfill();
```

**Comment by aeakett** [comment]
Awesome, that totally did the trick (that and installing es6-promise)... thanks!

**Comment by tnga** [comment]
Normally this issue occurs with node js version <= '0.12.0' (remark it's that latest version in ubuntu [trusty] main repository) cause promise feature it isn't include by default in node's bases modules. If it's your case, maybe is time to upgrade. Node release is on version 5.5.x now. If you are using linux (take a look here)[https://github.com/nodesource/distributions].
